[project]
name = "hello-lang-chain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain>=1.0",
    "langchain-anthropic>=1.3.0",
    "langchain-openai",
]

[dependency-groups]
dev = [
    "black>=25.12.0",
]
